### ISSUE TITLE
Blazor wasm observer undefined

### ISSUE THREAD

**Issue by jongio** [SveNord/Sve-Blazor-InfiniteScroll#3]
Heads up that I tried this with Blazor wasm and am getting this error:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'Observer.Initialize' ('Observer' was undefined).
      Error: Could not find 'Observer.Initialize' ('Observer' was undefined).
          at http://localhost:1080/_framework/blazor.webassembly.js:1:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (http://localhost:1080/_framework/blazor.webassembly.js:1:1247)
          at b (http://localhost:1080/_framework/blazor.webassembly.js:1:2989)
          at http://localhost:1080/_framework/blazor.webassembly.js:1:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (http://localhost:1080/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (http://localhost:1080/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (http://localhost:1080/_framework/dotnet.5.0.0.js:1:190800)
          at do_icall (http://localhost:1080/_framework/dotnet.wasm:wasm-function[10595]:0x194e46)v
```

**Comment by jongio** [comment]
I resolved this by manually coping this file to wwwroot/js and referencing it from html head.


https://github.com/SveNord/Sve-Blazor-InfiniteScroll/blob/master/Sve-Blazor-InfiniteScroll/wwwroot/js/Observer.js
